name: plan_et_b
description: Indie philosophical PWA game made in Flutter for Hack20 Hackathon.

environment:
  sdk: ">2.8.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #       sdk: flutter
  auto_size_text: any
  flare_flutter: ^2.0.5
  assets_audio_player: 2.0.7+9

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  pedantic: any
  effective_dart: any

# flutter_intl:
#   enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/foreground.flr
    - assets/animations/background.flr
    - assets/audio/cubedcanada+invaderloop.mp3
    - assets/audio/beam.wav
    - assets/images/StarfieldSimulation_rot.gif

  fonts:
    - family: Corruptor Clean LDR
      fonts:
        - asset: third-party/fonts/corruptor-clean-ldr/corruptor-clean-ldr.ttf

    - family: Corruptor LDR
      fonts:
        - asset: third-party/fonts/corruptor-ldr/corruptor-ldr.ttf

    - family: Polentical Neon
      fonts:
        - asset: third-party/fonts/polentical-neon/Polentical Neon Regular.ttf

        - asset: third-party/fonts/polentical-neon/Polentical Neon Italic.ttf
          style: italic